"""
Publish grades to Canvas.

This module:
1. Reads local grade.json and record.json.
2. Computes Canvas score from total_score_0_1 * points_possible.
3. Builds a feedback message containing:
   - total score
   - non-full-credit questions/subparts
   - feedback for those items
4. Publishes score/comment to Canvas.
5. Updates record.json immediately after each student.
6. Updates manifest.json after the publish run.

Default behavior should be dry-run from main.py.
"""

from __future__ import annotations

import os
import requests
from pathlib import Path
from typing import Any

from src.report_ops import get_assignment_points_possible
from src.storage_ops import ProjectStore, utc_now_iso


def format_score(value: Any, digits: int = 3) -> str:
    """Format numeric score safely."""

    if value is None:
        return ""

    try:
        return f"{float(value):.{digits}f}"
    except Exception:
        return str(value)


def build_non_full_credit_lines(grade_data: dict[str, Any]) -> list[str]:
    """
    Build feedback lines for non-full-credit questions/subparts.

    Expected grade_data structure:
    {
      "grading": {
        "questions": [
          {
            "question_id": "Q1",
            "question_score_0_1": 0.8,
            "subparts": [...]
          }
        ]
      }
    }
    """

    grading = grade_data.get("grading", {})
    questions = grading.get("questions", [])

    lines: list[str] = []

    for question in questions:
        question_id = question.get("question_id", "")
        question_score = question.get("question_score_0_1")

        try:
            question_score_float = float(question_score)
        except Exception:
            question_score_float = None

        if question_score_float is not None and question_score_float >= 0.999:
            continue

        lines.append(f"{question_id}: {format_score(question_score_float)} / 1.000")

        for subpart in question.get("subparts", []):
            subpart_id = subpart.get("subpart_id", "")
            subpart_score = subpart.get("score_0_1")

            try:
                subpart_score_float = float(subpart_score)
            except Exception:
                subpart_score_float = None

            if subpart_score_float is not None and subpart_score_float >= 0.999:
                continue

            feedback = subpart.get("feedback", "")
            evidence = subpart.get("evidence", [])

            line = f"  - {subpart_id}: {format_score(subpart_score_float)} / 1.000"

            if feedback:
                line += f" — {feedback}"

            if evidence and evidence != ["not found"]:
                short_evidence = "; ".join(str(x) for x in evidence[:2])
                line += f" Evidence: {short_evidence}"

            lines.append(line)

    return lines


def build_canvas_comment(
    grade_data: dict[str, Any],
    canvas_score: float,
    points_possible: float,
    publish_message: str | None = None,
    max_chars: int = 12000,
) -> str:
    """Build Canvas comment text."""

    total_score_0_1 = grade_data.get("total_score_0_1")
    total_score_sum = grade_data.get("total_score_sum")

    lines: list[str] = []

    if publish_message:
        lines.append(str(publish_message).strip())
        lines.append("")

    lines.append("Autograder feedback")
    lines.append(f"Total score: {format_score(canvas_score, 2)} / {format_score(points_possible, 2)}")
    lines.append(f"Normalized score: {format_score(total_score_0_1)}")

    if total_score_sum is not None:
        lines.append(f"Unweighted question-score sum: {format_score(total_score_sum)}")

    lines.append("")

    non_full_lines = build_non_full_credit_lines(grade_data)

    if non_full_lines:
        lines.append("Items not receiving full credit:")
        lines.extend(non_full_lines)
    else:
        lines.append("All graded items received full credit.")

    lines.append("")
    lines.append("Note: This feedback was generated by an automated grading assistant and may be reviewed by the course staff.")

    comment = "\n".join(lines).strip()

    if len(comment) > max_chars:
        comment = comment[: max_chars - 200].rstrip()
        comment += "\n\n[Feedback truncated because it exceeded the length limit.]"

    return comment


def post_grade_to_canvas(
    api_url: str,
    canvas_token: str,
    course_id: int,
    assignment_id: int,
    user_id: int,
    posted_grade: float,
    comment: str,
) -> dict[str, Any]:
    """Post one grade/comment to Canvas using the Canvas REST API."""

    api_url = str(api_url).rstrip("/")

    url = (
        f"{api_url}/api/v1/courses/{course_id}"
        f"/assignments/{assignment_id}"
        f"/submissions/{user_id}"
    )

    headers = {
        "Authorization": f"Bearer {canvas_token}",
    }

    data = {
        "submission[posted_grade]": str(posted_grade),
        "comment[text_comment]": comment,
    }

    response = requests.put(url, headers=headers, data=data, timeout=120)
    response.raise_for_status()

    return response.json()


def update_record_after_publish(
    record: dict[str, Any],
    canvas_score: float,
    points_possible: float,
    dry_run_publish: bool,
    comment: str,
    response_data: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Update record.json after publish or dry-run publish."""

    status = "dry_run_would_publish" if dry_run_publish else "published"

    record["publish"] = {
        "status": status,
        "published_at": None if dry_run_publish else utc_now_iso(),
        "dry_run_publish": dry_run_publish,
        "canvas_score": canvas_score,
        "points_possible": points_possible,
        "comment_preview": comment,
        "canvas_response_id": response_data.get("id") if response_data else None,
    }

    record.setdefault("history", []).append(
        {
            "event": status,
            "time": utc_now_iso(),
            "details": {
                "canvas_score": canvas_score,
                "points_possible": points_possible,
                "dry_run_publish": dry_run_publish,
            },
        }
    )

    return record


def update_record_after_publish_error(
    record: dict[str, Any],
    error: str,
    canvas_score: float | None = None,
) -> dict[str, Any]:
    """Update record.json after publish error."""

    record["publish"] = {
        "status": "publish_error",
        "published_at": None,
        "dry_run_publish": False,
        "canvas_score": canvas_score,
        "error": error,
    }

    record.setdefault("history", []).append(
        {
            "event": "publish_error",
            "time": utc_now_iso(),
            "details": {
                "error": error,
                "canvas_score": canvas_score,
            },
        }
    )

    return record


def publish_assignment_grades(
    course_match: Any,
    assignment_match: Any,
    base_dir: str | Path | None = None,
    api_url: str | None = None,
    canvas_token: str | None = None,
    dry_run_publish: bool = True,
    max_post_updates: int | None = None,
    publish_message: str | None = None,
    force_publish: bool = False,
) -> dict[str, Any]:
    """
    Publish local grades to Canvas.

    dry_run_publish=True:
    - Does not call Canvas PUT endpoint.
    - Still records what would be posted in record.json.

    force_publish=False:
    - If record.publish.status == "published", skip it.
    """

    course_id = int(course_match.id)
    assignment_id = int(assignment_match.id)

    project_store = ProjectStore(base_dir)
    course_store = project_store.course(course_id)
    assignment_store = course_store.assignment(assignment_id)

    manifest = assignment_store.load_manifest()
    student_records = manifest.get("student_records", {})

    points_possible = get_assignment_points_possible(assignment_store)

    if points_possible is None:
        raise ValueError("Cannot publish: points_possible is missing from assignment config/info.")

    if not api_url:
        api_url = os.getenv("CANVAS_API_URL")

    if not canvas_token:
        canvas_token = os.getenv("CANVAS_TOKEN")

    if not dry_run_publish:
        if not api_url:
            raise ValueError("Missing CANVAS_API_URL.")
        if not canvas_token:
            raise ValueError("Missing CANVAS_TOKEN.")

    stats = {
        "available_student_records": len(student_records),
        "processed": 0,
        "published": 0,
        "dry_run_would_publish": 0,
        "skipped_not_graded": 0,
        "skipped_missing_grade_json": 0,
        "skipped_already_published": 0,
        "skipped_no_score": 0,
        "errors": 0,
    }

    run_started_at = utc_now_iso()

    user_ids = [int(user_id) for user_id in student_records.keys()]
    publish_attempts = 0

    for index, user_id in enumerate(user_ids, start=1):
        if max_post_updates is not None and publish_attempts >= max_post_updates:
            break

        record = assignment_store.load_student_record(user_id)
        grade_data = assignment_store.load_grade_result(user_id)

        student_name = record.get("student", {}).get("name") or ""
        display_name = student_name or f"user_{user_id}"
        prefix = f"[{index}/{len(user_ids)}] {user_id} | {display_name}"

        stats["processed"] += 1

        if not grade_data:
            stats["skipped_missing_grade_json"] += 1
            print(f"{prefix} | skipped: missing grade.json")
            continue

        grading = record.get("grading", {})

        if grading.get("status") != "graded":
            stats["skipped_not_graded"] += 1
            print(f"{prefix} | skipped: not graded")
            continue

        publish_info = record.get("publish", {})

        if (
            not force_publish
            and publish_info.get("status") == "published"
            and not dry_run_publish
        ):
            stats["skipped_already_published"] += 1
            print(f"{prefix} | skipped: already published")
            continue

        total_score_0_1 = grade_data.get("total_score_0_1")

        if total_score_0_1 is None:
            stats["skipped_no_score"] += 1
            print(f"{prefix} | skipped: no score")
            continue

        try:
            canvas_score = float(total_score_0_1) * float(points_possible)
            comment = build_canvas_comment(
                grade_data=grade_data,
                canvas_score=canvas_score,
                points_possible=float(points_possible),
                publish_message=publish_message,
            )

            publish_attempts += 1

            if dry_run_publish:
                record = update_record_after_publish(
                    record=record,
                    canvas_score=canvas_score,
                    points_possible=float(points_possible),
                    dry_run_publish=True,
                    comment=comment,
                    response_data=None,
                )

                assignment_store.save_student_record(user_id, record)

                stats["dry_run_would_publish"] += 1

                print(
                    f"{prefix} | dry-run publish | "
                    f"score={format_score(canvas_score, 2)}/{format_score(points_possible, 2)}"
                )

            else:
                response_data = post_grade_to_canvas(
                    api_url=api_url,
                    canvas_token=canvas_token,
                    course_id=course_id,
                    assignment_id=assignment_id,
                    user_id=user_id,
                    posted_grade=canvas_score,
                    comment=comment,
                )

                record = update_record_after_publish(
                    record=record,
                    canvas_score=canvas_score,
                    points_possible=float(points_possible),
                    dry_run_publish=False,
                    comment=comment,
                    response_data=response_data,
                )

                assignment_store.save_student_record(user_id, record)

                stats["published"] += 1

                print(
                    f"{prefix} | published | "
                    f"score={format_score(canvas_score, 2)}/{format_score(points_possible, 2)}"
                )

        except Exception as e:
            error_message = str(e)

            record = update_record_after_publish_error(
                record=record,
                error=error_message,
                canvas_score=None,
            )

            assignment_store.save_student_record(user_id, record)

            stats["errors"] += 1

            short_error = error_message.replace("\n", " ")[:180]
            print(f"{prefix} | publish error | {short_error}")

            continue

    run_finished_at = utc_now_iso()

    manifest.setdefault("publish_runs", []).append(
        {
            "run_started_at": run_started_at,
            "run_finished_at": run_finished_at,
            "dry_run_publish": dry_run_publish,
            "max_post_updates": max_post_updates,
            "force_publish": force_publish,
            "publish_message": publish_message,
            "stats": stats,
        }
    )

    assignment_store.save_manifest(manifest)

    return {
        "course_id": course_id,
        "assignment_id": assignment_id,
        "dry_run_publish": dry_run_publish,
        "max_post_updates": max_post_updates,
        "force_publish": force_publish,
        "stats": stats,
    }